import { StrictMode, memo, useEffect } from 'react';
import { createRoot, Root } from 'react-dom/client';
import { BrowserRouter } from 'react-router-dom';
import { ThemeProvider } from '@mui/material/styles';
import CssBaseline from '@mui/material/CssBaseline';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import App from './App.tsx';
import { ErrorBoundary } from './components/common/ErrorBoundary';
import { ToastProvider } from './contexts/ToastContext';
import { crmThemeLight } from './lib/mui/crmTheme';
import './index.css';

// Create a client for React Query
const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      staleTime: 1000 * 60 * 5, // 5 minutes
      gcTime: 1000 * 60 * 10, // 10 minutes (formerly cacheTime)
      retry: 1,
    },
  },
});

// Defer heavy initialization to not block initial render
// These are executed in requestIdleCallback to avoid blocking the main thread
const deferInitialization = () => {
  if ('requestIdleCallback' in window) {
    requestIdleCallback(() => {
      import('./lib/sentry').then(({ initSentry }) => initSentry());
      import('./lib/errorReporting').then(({ setupGlobalErrorHandler }) => setupGlobalErrorHandler());
    });
  } else {
    // Fallback for browsers without requestIdleCallback
    setTimeout(() => {
      import('./lib/sentry').then(({ initSentry }) => initSentry());
      import('./lib/errorReporting').then(({ setupGlobalErrorHandler }) => setupGlobalErrorHandler());
    }, 100);
  }
};

// Start deferred initialization after first render
deferInitialization();

document.title = 'NRETech OneHub';

// Function to remove initial loader (CSP-compliant)
const hideInitialLoader = () => {
  const loader = document.getElementById('initial-loader');
  if (loader) {
    loader.style.opacity = '0';
    setTimeout(() => {
      loader.style.display = 'none';
    }, 300);
  }
};

export const ThemedApp = memo(() => {
  // Hide initial loader when React app mounts
  useEffect(() => {
    hideInitialLoader();
  }, []);

  return (
    <ThemeProvider theme={crmThemeLight}>
      <CssBaseline />
      <App />
    </ThemeProvider>
  );
});

const rootElement = document.getElementById('root') as HTMLElement & { __reactRoot?: Root };
if (rootElement && !rootElement.__reactRoot) {
  const root = createRoot(rootElement);
  // Mark the root element so we don't try to create root again
  rootElement.__reactRoot = root;
  root.render(
    <StrictMode>
      <QueryClientProvider client={queryClient}>
        <BrowserRouter>
          <ErrorBoundary>
            <ToastProvider>
              <ThemedApp />
            </ToastProvider>
          </ErrorBoundary>
        </BrowserRouter>
      </QueryClientProvider>
    </StrictMode>
  );
}

// Register service worker for offline support (generated by VitePWA)
// Only register the service worker in production builds to avoid
// interfering with the Vite dev server / HMR during development.
if (import.meta.env?.PROD && 'serviceWorker' in navigator) {
  window.addEventListener('load', () => {
    navigator.serviceWorker
      .register('/sw.js')
      .then((reg) => console.log('Service worker registered:', reg))
      .catch((err) => console.warn('Service worker registration failed:', err));
  });
} else if (!import.meta.env?.PROD && 'serviceWorker' in navigator) {
  // Dev convenience: if an older service worker is registered (from a
  // previous production build or earlier dev run), unregister it so the
  // Vite HMR client won't load a stale service-worker-served file that
  // tries to connect to an unavailable/old dev server and causes
  // `WebSocket closed without opened.` errors.
  window.addEventListener('load', async () => {
    try {
      const reg = await navigator.serviceWorker.getRegistration('/sw.js');
      if (reg) {
        await reg.unregister();
        console.info('Dev: unregistered existing /sw.js to avoid stale caching/HMR issues');
        // Best-effort clear of application caches which might still serve
        // cached assets from the old registration.
        if (caches && caches.keys) {
          const keys = await caches.keys();
          await Promise.all(keys.map((k) => caches.delete(k)));
        }
      }
    } catch (err) {
      console.debug('Dev: no service worker to unregister or failed to unregister', err);
    }
  });
}
